### ISSUE TITLE
Create and port custom 3D objects into Unity

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/VRIT-Work-Management#10]

**Comment by gavinjalberghini** [comment]
For this first issue simple objects without joints are fine. We will move into more complex things later. Also at request of the hardware team please look into virtual hand models when possible.

**Comment by Icefang35** [comment]
Simple 3D object has been created. Once I can send it to Unity, I will work on modeling a jointed object.

**Comment by gavinjalberghini** [comment]
Makes models and can import but cant bring the textures into unity. Opening new issues to make custom textures in unity and jointed objects in blender.
